In [14]:
import pandas as pd
import numpy as np
import gc
import time
from sklearn.metrics import roc_auc_score

df=pd.read_csv("df_select_feature_548.csv")

In [15]:
df

index  AMT_ANNUITY  AMT_CREDIT  AMT_GOODS_PRICE  AMT_INCOME_TOTAL  \
0           0      24700.5    406597.5         351000.0        202500.000   
1           1      35698.5   1293502.5        1129500.0        270000.000   
2           2       6750.0    135000.0         135000.0         67500.000   
3           3      29686.5    312682.5         297000.0        135000.000   
4           4      21865.5    513000.0         513000.0        121500.000   
5           5      27517.5    490495.5         454500.0         99000.000   
6           6      41301.0   1560726.0        1395000.0        171000.000   
7           7      42075.0   1530000.0        1530000.0        360000.000   
8           8      33826.5   1019610.0         913500.0        112500.000   
9           9      20250.0    405000.0         405000.0        135000.000   
10         10      21177.0    652500.0         652500.0        112500.000   
11         11      10678.5    148365.0         135000.0         38419.155   
12         12       5881.5     80865.0          67500.0         67500.000   
13         13      28966.5    918468.0         697500.0        225000.000   
14         14      32778.0    773680.5         679500.0        189000.000   
15         15      20160.0    299772.0         247500.0        157500.000   
16         16      26149.5    509602.5         387000.0        108000.000   
17         17      13500.0    270000.0         270000.0         81000.000   
18         18       7875.0    157500.0         157500.0        112500.000   
19         19      17563.5    544491.0         454500.0         90000.000   
20         20      21375.0    427500.0         427500.0        135000.000   
21         21      37561.5   1132573.5         927000.0        202500.000   
22         22      32521.5    497520.0         450000.0        450000.000   
23         23      23850.0    239850.0         225000.0         83250.000   
24         24      12703.5    247500.0         247500.0        135000.000   
25         25      11074.5    225000.0         225000.0         90000.000   
26         26      27076.5    979992.0         702000.0        112500.000   
27         27      23827.5    327024.0         270000.0        112500.000   
28         28      57676.5    790830.0         675000.0        270000.000   
29         29       9000.0    180000.0         180000.0         90000.000   
...       ...          ...         ...              ...               ...   
356221  48714      43366.5    547272.0         495000.0        360000.000   
356222  48715      57519.0    900000.0         900000.0        315000.000   
356223  48716      16398.0    318645.0         216000.0        135000.000   
356224  48717      13455.0    180000.0         180000.0         81000.000   
356225  48718      19530.0    360000.0         360000.0        225000.000   
356226  48719      35374.5    690313.5         549000.0        112500.000   
356227  48720      23134.5    323460.0         270000.0        171000.000   
356228  48721      37129.5    468333.0         382500.0        130500.000   
356229  48722      13284.0    166500.0         166500.0        220500.000   
356230  48723      16213.5    315000.0         315000.0         67500.000   
356231  48724      17707.5    514710.0         387000.0        112500.000   
356232  48725      24543.0    450000.0         450000.0         45000.000   
356233  48726      37917.0   1002339.0         846000.0        225000.000   
356234  48727      15291.0    149256.0         135000.0        180000.000   
356235  48728      38398.5    685386.0         585000.0        247500.000   
356236  48729      16020.0    135000.0         135000.0         81000.000   
356237  48730      40824.0    445095.0         405000.0        157500.000   
356238  48731      28890.0    450000.0         450000.0        112500.000   
356239  48732      54382.5    479700.0         450000.0        189000.000   
356240  48733      37764.0   1047771.0         904500.0        135000.000   
3562

In [16]:
train_df = df[df['TARGET'].notnull()]
test_df = df[df['TARGET'].isnull()]
del df
gc.collect()

0

In [5]:
#train_df.to_csv('train_df_select_feature.csv', index= False)
#test_df.to_csv('test_df_select_feature.csv', index= False)

In [17]:
feats = [f for f in train_df.columns if f not in ['TARGET','SK_ID_CURR','SK_ID_BUREAU','SK_ID_PREV','index']]

X = train_df[feats]
X = X.fillna(value = 0)
X = X.replace([np.inf, -np.inf], 0)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

for fe in X:
    X[fe] = scaler.fit_transform(X[fe].values.reshape(-1,1))
    
target = train_df['TARGET']
# Reshape (one-hot)
y = np.zeros([len(target), len(np.unique(target))])
y[:, 0] = target == 0 # 0
y[:, 1] = target == 1 # 1
print(y)

X_test = test_df[feats]
X_test = X_test.fillna(value = 0)
X_test = X_test.replace([np.inf, -np.inf], 0)

for fe in X_test:
    X_test[fe] = scaler.fit_transform(X_test[fe].values.reshape(-1,1))
#y = scaler.fit_transform(y.values.reshape(-1,1))

# split data
from sklearn.model_selection import train_test_split
X_train, X_valid, y_train, y_valid = train_test_split(X, y,test_size=0.2,stratify=y[:, 0])#, random_state=42)

print (X_train.shape)
print (X_valid.shape)
print (y_train.shape)
print (y_valid.shape)

C:\Users\Administrator\Anaconda2\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [1. 0.]]
(246005, 545)
(61502, 545)
(246005, 2)
(61502, 2)


In [18]:
# Build Deep Neural Network
import tensorflow as tf
# Fixed graph parameters
N_HIDDEN_1 = 80
N_HIDDEN_2 = 80
N_HIDDEN_3 = 40

n_classes = 2

# Learning parameters
LEARNING_RATE = 0.001
N_EPOCHS = 10000
N_ITERATIONS = 400
BATCH_SIZE = 250

# Graph
tf.reset_default_graph()

# Define placeholders
    
INPUTS = tf.placeholder(tf.float32, shape=(None, X_train.shape[1]), name='INPUTS')
LABELS = tf.placeholder(tf.int32, shape=(None, n_classes), name='LABELS')
train_mode = tf.placeholder(tf.bool)

INPUTS = tf.identity(INPUTS)
# Define the network layers. 
# Overfitting is a challenge so add L2 regularisation to weights in 1st layer & 
# a couple of dropout layers
with tf.name_scope('dnn'):
    hidden_layer_1 = tf.layers.dense(inputs=INPUTS,
                                     units=N_HIDDEN_1,
                                     name='first_hidden_layer',
                                     kernel_regularizer=tf.contrib.layers.l2_regularizer(scale=0.3))
    hidden_layer_1 = tf.layers.batch_normalization(hidden_layer_1, training=train_mode)
    hidden_layer_1 = tf.nn.relu(hidden_layer_1)
    
    drop_layer_1 = tf.layers.dropout(inputs=hidden_layer_1, 
                                     rate=0.4, 
                                     name='first_dropout_layer',
                                     training=train_mode)

    hidden_layer_2 = tf.layers.dense(inputs=drop_layer_1,
                                     units=N_HIDDEN_2,
                                     name='second_hidden_layer',
                                     kernel_regularizer=tf.contrib.layers.l2_regularizer(scale=0.1))
    hidden_layer_2 = tf.layers.batch_normalization(hidden_layer_2, training=train_mode)
    hidden_layer_2 = tf.nn.relu(hidden_layer_2)
                                     
    drop_layer_2 = tf.layers.dropout(inputs=hidden_layer_2, 
                                     rate=0.2, 
                                     name='second_dropout_layer',
                                     training=train_mode)

    hidden_layer_3 = tf.layers.dense(inputs=drop_layer_2,
                                     units=N_HIDDEN_3,
                                     name='third_hidden_layer')
    hidden_layer_3 = tf.layers.batch_normalization(hidden_layer_3, training=train_mode)
    hidden_layer_3 = tf.nn.relu(hidden_layer_3)

    logits = tf.layers.dense(inputs=hidden_layer_3,
                             units=n_classes,
                             name='outputs')

# Define the loss function for training as cross entropy
with tf.name_scope('loss'):
    xent = tf.nn.softmax_cross_entropy_with_logits_v2(labels=LABELS, logits=logits)
    loss = tf.reduce_mean(xent, name='loss')

# Define the optimiser
with tf.name_scope('train'):
    optimiser = tf.train.AdamOptimizer()  # AdagradOptimizer(learning_rate=LEARNING_RATE)
    train_step = optimiser.minimize(loss)

# Output the class probabilities to I can get the AUC
with tf.name_scope('eval'):
    predict = tf.argmax(logits,axis=1, name='class_predictions') 
    predict_proba = tf.nn.softmax(logits, name='probability_predictions')
    

# Initialisation node and saver
init = tf.global_variables_initializer()
saver = tf.train.Saver()

In [19]:
df_y_train = pd.DataFrame(y_train)

In [20]:
np_X_train=X_train.values
np_X_train

array([[0.04796038, 0.0505618 , 0.06111111, ..., 0.        , 0.        ,
        0.        ],
       [0.05232041, 0.05617978, 0.06666667, ..., 0.        , 0.        ,
        0.        ],
       [0.18186575, 0.3258427 , 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.14597394, 0.31044944, 0.27777778, ..., 0.        , 0.        ,
        0.49479167],
       [0.06653412, 0.06717978, 0.05888889, ..., 0.        , 0.        ,
        0.        ],
       [0.16925653, 0.16701348, 0.16333333, ..., 0.        , 0.50684932,
        0.38541667]])

In [21]:
def get_feed_dict(batch_X, batch_y=None,training=False):
    """ Return a feed dict for the graph """ 
    feed_dict = {INPUTS: batch_X,
                }
    if batch_y is not None:
        feed_dict[LABELS] = batch_y
    # Training mode or not
    feed_dict[train_mode] = training  
    return feed_dict


train_auc, valid_auc = [], []
n_rounds_not_improved = 0
early_stopping_epochs = 20
with tf.Session() as sess:

    init.run()
    
    # Begin epoch loop
    print('Training for {} iterations over {} epochs with batchsize {} ...'
          .format(N_ITERATIONS, N_EPOCHS, BATCH_SIZE))
    iteration = 0
    for epoch in range(N_EPOCHS):
        # Iteration loop
        
        for iteration in range(len(X_train) // BATCH_SIZE):
            # Get random selection of data for batch GD. Upsample positive classes to make it
            # balanced in the training batch
            pos_ratio = 0.5
            pos_idx = np.random.choice(np.where(y_train[:, 1] == 1)[0], # 1
                                       size=int(np.round(BATCH_SIZE*pos_ratio)))
            neg_idx = np.random.choice(np.where(y_train[:, 1] == 0)[0], # 0
                                       size=int(np.round(BATCH_SIZE*(1-pos_ratio))))
            idx = np.concatenate([pos_idx, neg_idx])
            
            # Run training
            extra_update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
            sess.run([train_step, extra_update_ops], 
                     feed_dict=get_feed_dict(np_X_train[idx, :], y_train[idx, :], 1)) # type=numpy....
            

        # Check on the AUC
        y_pred_train, y_prob_train = sess.run(
            [predict, predict_proba], feed_dict=get_feed_dict(X_train, y_train, False))
        
        print('y_pred_train======'.format(y_pred_train))
        print(y_pred_train)
        print('y_prob_train======'.format(y_prob_train))
        print(y_prob_train)
        train_auc.append(roc_auc_score(y_train[:, 1], y_prob_train[:, 1]))
        
        y_pred_val, y_prob_val = sess.run(
            [predict, predict_proba], feed_dict=get_feed_dict(X_valid, y_valid, False))
        
        valid_auc.append(roc_auc_score(y_valid[:, 1], y_prob_val[:, 1]))
        
        # Early stopping
        if epoch > 1:
            best_epoch_so_far = np.argmax(valid_auc[:-1])
            if valid_auc[epoch] <= valid_auc[best_epoch_so_far]:
                n_rounds_not_improved += 1
            else:
                n_rounds_not_improved = 0       
            if n_rounds_not_improved > early_stopping_epochs:
                print('Early stopping due to no improvement after {} epochs.'
                      .format(early_stopping_epochs))
                break
        print('Epoch = {}, Train AUC = {:.8f}, Valid AUC = {:.8f}'
              .format(epoch, train_auc[epoch], valid_auc[epoch]))

    # Once trained, make predictions
    print('Training complete.')
    y_prob = sess.run(predict_proba, feed_dict=get_feed_dict(X_test, None, False))

Training for 400 iterations over 10000 epochs with batchsize 250 ...
y_pred_train======
[0 0 0 ... 0 1 1]
y_prob_train======
[[0.80687815 0.1931218 ]
 [0.70072716 0.29927287]
 [0.88359296 0.11640703]
 ...
 [0.55528176 0.4447182 ]
 [0.46572164 0.5342784 ]
 [0.40964225 0.5903577 ]]
Epoch = 0, Train AUC = 0.77572433, Valid AUC = 0.75752504
y_pred_train======
[0 0 0 ... 0 1 1]
y_prob_train======
[[0.76142746 0.23857261]
 [0.70761675 0.2923833 ]
 [0.91234124 0.08765883]
 ...
 [0.5281317  0.47186828]
 [0.33739436 0.6626057 ]
 [0.39885336 0.60114664]]
Epoch = 1, Train AUC = 0.78349305, Valid AUC = 0.76354428
y_pred_train======
[0 0 0 ... 1 1 1]
y_prob_train======
[[0.8201038  0.17989619]
 [0.6719141  0.32808587]
 [0.9073787  0.09262129]
 ...
 [0.43624172 0.56375825]
 [0.3633559  0.6366441 ]
 [0.39010754 0.6098924 ]]
Epoch = 2, Train AUC = 0.79257133, Valid AUC = 0.76665104
y_pred_train======
[0 0 0 ... 0 1 1]
y_prob_train======
[[0.8514851  0.14851496]
 [0.7582008  0.24179916]
 [0.96421814 0.

In [22]:
out_df = pd.DataFrame({'SK_ID_CURR': test_df['SK_ID_CURR'], 'TARGET': y_prob[:, 1]})
out_df.to_csv('dnn_submission02.csv', index=False)